# MD033/no-inline-html : Inline HTML : https://github.com/DavidAnson/markdownlint/blob/v0.35.0/doc/md033.md
MD033:
  # This is meant to track: https://docs.github.com/en/get-started/writing-on-github
  allowed_elements:
    - "a"
    - "br"
    - "details"
    - "summary"
# MD013/line-length : Line length : https://github.com/DavidAnson/markdownlint/blob/v0.35.0/doc/md013.md
MD013:
  # Conforms to .clang-format ColumnLimit
  # Update the comment in .clang-format if we no-longer tie these two column limits.
  code_block_line_length: 119
